### ISSUE TITLE
URL Bot "corrects" magnet links!

### ISSUE THREAD

**Issue by ErikUden** [yingziwu/url_bot#1]
![image](https://user-images.githubusercontent.com/52011431/156928236-e4e71e80-87a5-4f27-b1e2-671a38281ade.png)

This happened to me on the Fediverse today! A link to the post can be found here:
https://social.uden.ai/@url@bgme.me/posts/AH8POk52bAxxJn45Cq

I really like the idea of the bot and fully support tracker removal of links, many people in my family often send me unnecessarily long links with the only purpose of tracking me, however, magnet links (hashes of torrent files) do not include "tracking URLs". Magnet links do not use the HTTPS/HTTP, as they only function via the BitTorrent Protocol. Magnet links cannot be opened in a browser, but require an application like Tixati or qBittorrent to open! They lead to a torrent file which connects you to a swarm of people that have the contents of that file downloaded so that you can receive it in a decentralized manner. I am not sure if you have heard of the basics of torrenting yet, but this was the best explanation I could give.

Many magnet links and torrent files include "tracker" links, but they are not like traditional trackers that track and survey individuals, such trackers (like tracker.openbittorrent.com) track the individuals having that file to allow for decentralized networking. A tracker in torrenting is an integral part of the torrent, without it, torrenting would not work. 

This was simply a small mistake. Please modify your bot to exclude links that begin with "magnet:" otherwise please keep it running!

Also, thanks to this "mistake", I was made aware of your social media platform and your great posts, so I am very glad it happened!

I assume you are https://social.uden.ai/@bgme@bgme.me ?
Very nice to meet you! 
I will contact you on Matrix soon, glad to see another open source enthusiast and FOSS developer!!

**Comment by yingziwu** [comment]
Thanks for report.
